import type { Metadata } from 'next';
import Link from 'next/link';
import { PolicyDocument } from '@/components/PolicyDocument';
export const metadata: Metadata = { title: 'Terms', description: 'Terms for the Pulse website and private evaluation service.', alternates: { canonical: '/terms' } };

export default function TermsPage() {
  return <PolicyDocument title="Website and preview terms">
    <p>Cameron Low personally operates this website and hosted preview using the Pulse brand from Ontario, Canada. A separately agreed evaluation arrangement takes precedence where it addresses the same subject.</p>
    <section><h2>Availability and fees</h2><p>Pulse is in private preview. There is no public purchase, subscription or payment collection. Planned capabilities and deployment options do not promise delivery dates, production readiness or service levels. Existing users should keep independent copies of information they need. Access and features may change; material changes affecting an agreed evaluation will be communicated.</p></section>
    <section><h2>Permitted use and your data</h2><p>Use the service only for sites, data, monitoring targets and integrations you are authorized to manage. Provide the notices, permissions and consent your collection requires. Do not collect sensitive personal information, credentials or payment-card data through analytics events. Do not abuse access controls, send spam, interfere with services or use monitoring to access private systems without authorization.</p><p>You retain your rights to submitted content and authorize the processing needed to provide the features you use. Only publish status pages, create share links, select notification recipients or send data to AI when you have authority to disclose that information. Check recipients, permissions and expiry settings. The <Link href="/privacy">privacy notice</Link> explains processing and deletion limits.</p></section>
    <section><h2>AI, third parties and software</h2><p>AI summaries are fallible and require review before relying on them. Your chosen providers and integrations have their own terms. Website content and branding remain with their rights holders. Any separately supplied software licence continues to govern that software; this website does not promise public source availability or grant a licence to proprietary material.</p></section>
    <section><h2>Concerns and applicable law</h2><p>Report suspected security issues privately to the contact below with safe reproduction details. Avoid disruptive testing or collecting other people’s data. No bounty or response-time promise is made.</p><p>Information is provided for evaluation and can contain errors or be interrupted. Nothing here excludes rights or liabilities that cannot lawfully be excluded. Ontario law and applicable Canadian federal law govern, subject to mandatory protections where you live. Contact Cameron to discuss a dispute, access need or correction. Updated terms will have a new effective date.</p></section>
  </PolicyDocument>;
}
