import type { Metadata } from 'next';
import { PolicyDocument } from '@/components/PolicyDocument';
export const metadata: Metadata = { title: 'Privacy', description: 'Website and hosted-preview data handling by Cameron Low, operator of Pulse.', alternates: { canonical: '/privacy' } };

export default function PrivacyPage() {
  return <PolicyDocument title="Privacy">
    <p>Cameron Low personally operates pulsewebanalytics.com and its hosted Pulse preview from Ontario, Canada. Pulse is a brand. This notice covers the website and Cameron-operated service; an independent installation is controlled by its own operator.</p>
    <section><h2>Public website and contact</h2><p>Web infrastructure processes IP addresses, requested URLs, times, browser details, response codes and referring pages to serve and protect the website. Hostinger infrastructure hosts the service and its database in the United States. Routine web logs rotate daily, keeping up to 14 rotated files; relevant incident records may be retained longer.</p><p>Optional first-party analytics on this public website have been disabled. Records collected previously may remain in the analytics database until deletion; there is no automatic analytics expiry. The earlier tracker used a random visit identifier in session storage with a 30-minute inactivity limit and respected Do Not Track. The separate tracker offered to participating sites is described below.</p><p>If you email Cameron, your address, message and attachments are used to respond and manage the request. The published contact uses Cloudflare Email Routing and a Google-hosted inbox, with processing potentially outside Canada. Emailing does not subscribe you to marketing. Correspondence has no automatic deletion deadline and is retained for the conversation, an agreed relationship or a legal or security need.</p></section>
    <section><h2>Accounts and access</h2><p>The hosted product is a private preview. Public account creation is closed; existing invited users can sign in. Accounts store a name, email, optional profile image, organization memberships and either a password hash or Google sign-in account information. Google sign-in uses identity/profile information and provider tokens; it does not request Gmail message access. Authentication uses session and security cookies. Signing out ends browser access but does not delete the account.</p></section>
    <section><h2>Analytics collected for participating sites</h2><p>The site operator decides whether and where to install Pulse and must explain its use to visitors and obtain consent when required. The default tracker respects Do Not Track and does not set visitor cookies. It uses session storage for a random visit identifier, renewed after 30 minutes of inactivity. Cookie-free collection can still involve personal information.</p><p>Pulse receives page URLs and stores host/path, visit identifiers, referring-page information, campaign tags, browser/operating-system/device categories, language and available country information. New referrer records omit credentials, query parameters and fragments. Custom events may include names, properties, order references or revenue amounts, and optional web-vital performance measurements. IP addresses are processed by the server and hashed for in-memory rate limiting; web logs can separately contain IP addresses. Do not put sensitive information in URLs, campaign tags or event properties.</p></section>
    <section><h2>Reports, sharing, monitoring and AI</h2><p>Organization members see data according to their roles. A share link exposes the selected report to anyone holding it until revoked or its configured expiry; a link may have no expiry. Public status pages expose the information their owner publishes. Configured email and webhook notifications send report or incident details to their destinations and delivery providers. Monitoring stores target addresses, checks, timings, status and incident details.</p><p>Using AI chat sends your messages and the selected site’s recent summary metrics, top page paths, referrers and event summaries to the configured provider: OpenAI, Anthropic or Perplexity. Those services may process data outside Canada under their own terms and retention rules. Ask your instance operator which provider is configured before sending confidential information. AI is optional and its output can be wrong. Agent integrations receive data authorized by their token scopes; access and action records may be retained for security.</p></section>
    <section><h2>Retention, deletion and choices</h2><p>Analytics, account, monitoring and operational records currently have no universal automatic expiry. Authorized owners can delete sites or organizations and their related database records using product controls. Account closure and information requests are handled by Cameron. Deleting a site does not erase its copies in previously sent emails, downloaded reports, another provider or a recipient’s possession. Revoking a link stops future access; it does not recall copies.</p><p>Backups and incident records can outlast active records. A verified universal backup-erasure deadline has not been established for this preview; Cameron will explain the applicable remaining copies and limits when handling a request. This limitation must be resolved for any engagement needing a contractual deletion deadline.</p><p>You can ask to access, correct or delete personal information, withdraw consent where processing depends on it, or make a complaint. Proportionate verification and legal obligations may limit a request. If another operator collected your visit through Pulse, contact that operator first so they can identify the relevant records. Cameron does not sell personal information or share it for targeted advertising.</p></section>
    <section><h2>Updates</h2><p>Material changes to collection or use will be explained before the affected new activity begins. This notice’s effective date records revisions. Hosting, integrations and retention on independent installations are the responsibility of their operators.</p></section>
  </PolicyDocument>;
}
