'use client';

import { useCallback, useEffect, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import { Button, Card, Title, Badge } from '@velocityuikit/velocityui';
import { PageTransition } from '@/components/motion';
import type { InsightSummary } from '@/types';

const severityVariant: Record<string, 'info' | 'warning' | 'danger'> = {
  info: 'info',
  warning: 'warning',
  critical: 'danger',
};

export default function InsightsPage() {
  const siteId = useSearchParams().get('siteId') || '';
  const [insights, setInsights] = useState<InsightSummary[]>([]);

  const loadInsights = useCallback(async () => {
    if (!siteId) return;
    const res = await fetch(`/api/insights?siteId=${siteId}`);
    if (res.ok) setInsights(await res.json());
  }, [siteId]);

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    loadInsights();
  }, [loadInsights]);

  async function dismiss(id: string) {
    const res = await fetch(`/api/insights/${id}`, { method: 'PUT' });
    if (res.ok) loadInsights();
  }

  return (
    <PageTransition>
      <div className="pulse-page">
        <div className="pulse-page-header">
          <div>
            <Title level="h1" size="lg">Insights</Title>
            <p style={{ color: 'var(--pulse-text-secondary)', fontSize: '0.875rem', marginTop: '0.25rem' }}>
              Generated by the scheduled insights job from analytics, revenue, uptime, funnel, and performance data.
            </p>
          </div>
        </div>

        <div style={{ display: 'grid', gap: '1rem' }}>
          {insights.length === 0 ? (
            <Card variant="shadow">
              <Card.Body>
                <p style={{ color: 'var(--pulse-text-secondary)', margin: 0 }}>
                  No active insights yet. Run the insights cron endpoint after data has been collected.
                </p>
              </Card.Body>
            </Card>
          ) : insights.map((insight) => (
            <Card key={insight.id} variant="shadow">
              <Card.Body>
                <div style={{ display: 'flex', justifyContent: 'space-between', gap: '1rem', alignItems: 'flex-start' }}>
                  <div>
                    <Badge variant={severityVariant[insight.severity] ?? 'info'} size="sm">{insight.severity}</Badge>
                    <h2 style={{ fontSize: '1rem', margin: '0.625rem 0 0.375rem' }}>{insight.title}</h2>
                    <p style={{ color: 'var(--pulse-text-secondary)', margin: 0 }}>{insight.body}</p>
                    <p style={{ color: 'var(--pulse-text-secondary)', fontSize: '0.75rem', margin: '0.75rem 0 0' }}>
                      Created {new Date(insight.createdAt).toLocaleString()}
                    </p>
                  </div>
                  <Button variant="ghost" size="sm" onClick={() => dismiss(insight.id)}>Dismiss</Button>
                </div>
              </Card.Body>
            </Card>
          ))}
        </div>
      </div>
    </PageTransition>
  );
}
